### ISSUE TITLE
Kompatibilität mit XJustiz 3.4.1

### ISSUE THREAD

**Issue by librelegal** [digidigital/openXJV#1]
Laut https://github.com/digidigital/openXJV unterstützt openXJV den XJustiz-Standard in den Versionen 3.3.1, 3.2.1 sowie 2.4.1. 

Ab November 2023 gilt aber der neue Standard 3.4.1 (https://xjustiz.justiz.de/xjustiz_3_4_1/index.php). 
Wird dieser neue Standard ab November 2023 auch bereits unterstützt?

j-lawyer hat den neuen Standard bereits implementiert (https://github.com/jlawyerorg/j-lawyer-org/issues/2098) und plant den Einbau von openXJV (https://github.com/jlawyerorg/j-lawyer-org/issues/1200), was aber nur Sinn macht, wenn der neue Standard unterstützt wird.

**Comment by digidigital** [comment]
Wird bereits unterstützt - Readme-Text auf Github war noch nicht auf dem aktuellen Stand ;)
